defaults:
  - _self_

exp:
  name: "unnamed"



gpu_index: 0
gamma: 0.99 
tau: 0.95
log_std: -0.0
l2_reg: 0.001
learning_rate: 0.0003
clip_epsilon: 0.2
num_threads: 1
train_log_interval: 1
save_model_interval: 1 # 0 = Don't save
min_batch_size: 2048
eval_batch_size: 2048


pretrained_path: #"outputs/2023-01-11/10-01-32/learned_models/EdgeRIC_ppo.p"


algorithm: "PPO"
num_seeds: 1 # Number of seeded trains; set to 0 for only evaluation
num_iters: 150 # Number of iterations to train for
num_eval_episodes: 10 # Number of evaluation episodes to test for (to compare against baseline agents)
visualize_policy: False

env: "EdgeRICApp1"
render: False

env_config:
  normalize_state_space: False
  augment_state_space: True # Add backpressure to state space
  delay_state: 0
  delay_action: 1
  seed: -1 # No seed
  T: 1000
  num_RBGs: 17 # Modify according to MHz of operation
  num_UEs: 2
  backlog_population: #Currently uniform arrival TODO Poisson? 
    - [10, 8598.800000000001] # TTIs between chunk arrivals ,chunk_size(bytes) - UE1
    - [10, 25102.4] # TTIs between chunk arrivals ,chunk_size(bytes) - UE2
  playout_process:
    - [10, 600, 10000] # TTI between playouts, size of playout chunk (bytes), size of GoP(bytes) - UE1
    - [10, 27100, 30000] # TTI between playouts, size of playout chunk (bytes) - size of GoP(bytes) - UE2

  cqi_trace: "stream_rl/envs/cqi_traces/data.csv" # Train Trace for 2 UEs
  cqi_trace_eval: "stream_rl/envs/cqi_traces/data.csv" # Eval Trace for 2 UEs
  reward: "stall_based"
  base_station:
    max_len: 300000 # Bytes
  application:
    max_len: 999999 # Bytes
  
  # cqi_map: {    # [Mean throughput, Std] (Mbps)
  #           1 : [0.4432, 0.0],
  #           2 : [0.6394, 0.0],
  #           3 : [0.6990, 0.0],
  #           4 : [0.9112, 0.0],
  #           5 : [1.0014, 0.0],
  #           6 : [1.3261, 0.0],
  #           7 : [1.5028, 0.0],
  #           8 : [1.9077, 0.0],
  #           9 : [2.0347, 0.0],
  #           10 : [2.0542, 0.0],
  #           11 : [2.0479, 0.0],
  #           12 : [2.0517, 0.0],
  #           13 : [2.0303, 0.0],
  #           14 : [2.0239, 0.0],
  #           15 : [2.0477, 0.0],
  #           }
  cqi_map: {    # [Mean throughput, Std] (Mbps)
            1 : [0.4432, 0.2206],
            2 : [0.6394, 0.2047],
            3 : [0.6990, 0.3575],
            4 : [0.9112, 0.2882],
            5 : [1.0014, 0.4647],
            6 : [1.3261, 0.3873],
            7 : [1.5028, 0.5879],
            8 : [1.9077, 0.3314],
            9 : [2.0347, 0.3120],
            10 : [2.0542, 0.3142],
            11 : [2.0479, 0.3019],
            12 : [2.0517, 0.3086],
            13 : [2.0303, 0.3170],
            14 : [2.0239, 0.3053],
            15 : [2.0477, 0.2942],
            }
    
    
  