# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: control_mcs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='control_mcs.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11\x63ontrol_mcs.proto\"-\n\x0bmcs_control\x12\x11\n\tran_index\x18\x01 \x01(\r\x12\x0b\n\x03mcs\x18\x02 \x03(\x02\x62\x06proto3')
)




_MCS_CONTROL = _descriptor.Descriptor(
  name='mcs_control',
  full_name='mcs_control',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ran_index', full_name='mcs_control.ran_index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mcs', full_name='mcs_control.mcs', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=66,
)

DESCRIPTOR.message_types_by_name['mcs_control'] = _MCS_CONTROL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

mcs_control = _reflection.GeneratedProtocolMessageType('mcs_control', (_message.Message,), dict(
  DESCRIPTOR = _MCS_CONTROL,
  __module__ = 'control_mcs_pb2'
  # @@protoc_insertion_point(class_scope:mcs_control)
  ))
_sym_db.RegisterMessage(mcs_control)


# @@protoc_insertion_point(module_scope)
