# This example configuration outlines how to configure the srsRAN Project CU/DU to use an O-RU and split 7.2. This is specifically for use
# with the Picocom PC802 SCB. This config will create a single TDD cell transmitting in band 78, with 20 MHz bandwidth and 30 kHz sub-carrier-spacing.
# The parameters used to configure the RU are found in the `ru_ofh` sub-section. This configuration makes used of the OFH Lib from SRS to enable split 7.2.

amf:
  addr: 127.0.1.100                                               
  bind_addr: 127.0.0.1                                            

ru_ofh:
  t1a_max_cp_dl: 350                                              
  t1a_min_cp_dl: 250                                              
  t1a_max_cp_ul: 250                                              
  t1a_min_cp_ul: 150                                              
  t1a_max_up: 200                                                 
  t1a_min_up: 80                                                  
  ta4_max: 300                                                    
  ta4_min: 10                                                     
  is_prach_cp_enabled: false                                      
  compr_method_ul: bfp                                            
  compr_bitwidth_ul: 9                                            
  compr_method_dl: bfp                                            
  compr_bitwidth_dl: 9                                            
  compr_method_prach: bfp                                         
  compr_bitwidth_prach: 9                                         
  iq_scaling: 1.0                                                 
  cells:
    - network_interface: enp1s0f0                                 
      ru_mac_addr: ce:fc:6c:09:a6:cd                              
      du_mac_addr: 80:61:5f:0d:df:aa                              
      vlan_tag_cp: 3                                              
      vlan_tag_up: 3                                              
      prach_port_id: [0]                                          
      dl_port_id: [0]                                             
      ul_port_id: [0]                                             

cell_cfg:
  dl_arfcn: 625000                                                
  band: 78                                                        
  channel_bandwidth_MHz: 20                                       
  common_scs: 30                                                  
  plmn: "00101"                                                   
  tac: 7                                                          
  pci: 1                                                          
  prach:
    prach_config_index: 159                                       
    prach_root_sequence_index: 1                                  
    zero_correlation_zone: 0                                      
    prach_frequency_start: 0                                      
  tdd_ul_dl_cfg:
    nof_dl_slots: 7
    nof_ul_slots: 2

log:
  filename: /tmp/gnb.log                                          
  all_level: warning                                              

pcap:
  mac_enable: false                                               
  mac_filename: /tmp/gnb_mac.pcap                                 
  ngap_enable: false                                              
  ngap_filename: /tmp/gnb_ngap.pcap                               
