# This example configuration outlines how to configure the srsRAN Project gNB to create a single TDD cell
# transmitting in band 78, with 20 MHz bandwidth and 30 kHz sub-carrier-spacing. A USRP B200 is configured 
# as the RF frontend using split 8. Note in this example an external clock source is not used, so the sync 
# is not defined and the default is used. 

amf:
  addr: 127.0.1.100                                               
  bind_addr: 127.0.0.1                                          

ru_sdr:
  device_driver: uhd                                              
  device_args: type=b200,num_recv_frames=64,num_send_frames=64    
  srate: 23.04                                                    
  otw_format: sc12  
  tx_gain: 80                                                     
  rx_gain: 40                                                     

cell_cfg:
  dl_arfcn: 632628                                               
  band: 78                                                       
  channel_bandwidth_MHz: 20                                      
  common_scs: 30                                                 
  plmn: "00101"                                                  
  tac: 7                                                         
  pci: 1                                                         

log:
  filename: /tmp/gnb.log                                         
  all_level: warning                                             

pcap:
  mac_enable: false                                        
  mac_filename: /tmp/gnb_mac.pcap                          
  ngap_enable: false                                       
  ngap_filename: /tmp/gnb_ngap.pcap                        