// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control_mcs.proto

#include "control_mcs.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

class mcs_controlDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<mcs_control>
      _instance;
} _mcs_control_default_instance_;
namespace protobuf_control_5fmcs_2eproto {
static void InitDefaultsmcs_control() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_mcs_control_default_instance_;
    new (ptr) ::mcs_control();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mcs_control::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_mcs_control =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsmcs_control}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_mcs_control.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mcs_control, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mcs_control, ran_index_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mcs_control, mcs_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::mcs_control)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_mcs_control_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "control_mcs.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\021control_mcs.proto\"-\n\013mcs_control\022\021\n\tra"
      "n_index\030\001 \001(\r\022\013\n\003mcs\030\002 \003(\002b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 74);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "control_mcs.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_control_5fmcs_2eproto

// ===================================================================

void mcs_control::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int mcs_control::kRanIndexFieldNumber;
const int mcs_control::kMcsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

mcs_control::mcs_control()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_control_5fmcs_2eproto::scc_info_mcs_control.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:mcs_control)
}
mcs_control::mcs_control(const mcs_control& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      mcs_(from.mcs_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ran_index_ = from.ran_index_;
  // @@protoc_insertion_point(copy_constructor:mcs_control)
}

void mcs_control::SharedCtor() {
  ran_index_ = 0u;
}

mcs_control::~mcs_control() {
  // @@protoc_insertion_point(destructor:mcs_control)
  SharedDtor();
}

void mcs_control::SharedDtor() {
}

void mcs_control::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* mcs_control::descriptor() {
  ::protobuf_control_5fmcs_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_control_5fmcs_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const mcs_control& mcs_control::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_control_5fmcs_2eproto::scc_info_mcs_control.base);
  return *internal_default_instance();
}


void mcs_control::Clear() {
// @@protoc_insertion_point(message_clear_start:mcs_control)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  mcs_.Clear();
  ran_index_ = 0u;
  _internal_metadata_.Clear();
}

bool mcs_control::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:mcs_control)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 ran_index = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &ran_index_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated float mcs = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_mcs())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(21u /* 21 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 18u, input, this->mutable_mcs())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:mcs_control)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:mcs_control)
  return false;
#undef DO_
}

void mcs_control::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:mcs_control)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 ran_index = 1;
  if (this->ran_index() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->ran_index(), output);
  }

  // repeated float mcs = 2;
  if (this->mcs_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(2, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _mcs_cached_byte_size_));
    ::google::protobuf::internal::WireFormatLite::WriteFloatArray(
      this->mcs().data(), this->mcs_size(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:mcs_control)
}

::google::protobuf::uint8* mcs_control::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:mcs_control)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 ran_index = 1;
  if (this->ran_index() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->ran_index(), target);
  }

  // repeated float mcs = 2;
  if (this->mcs_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      2,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _mcs_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteFloatNoTagToArray(this->mcs_, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mcs_control)
  return target;
}

size_t mcs_control::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mcs_control)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated float mcs = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->mcs_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _mcs_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // uint32 ran_index = 1;
  if (this->ran_index() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->ran_index());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void mcs_control::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mcs_control)
  GOOGLE_DCHECK_NE(&from, this);
  const mcs_control* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const mcs_control>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mcs_control)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mcs_control)
    MergeFrom(*source);
  }
}

void mcs_control::MergeFrom(const mcs_control& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mcs_control)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  mcs_.MergeFrom(from.mcs_);
  if (from.ran_index() != 0) {
    set_ran_index(from.ran_index());
  }
}

void mcs_control::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mcs_control)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void mcs_control::CopyFrom(const mcs_control& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mcs_control)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool mcs_control::IsInitialized() const {
  return true;
}

void mcs_control::Swap(mcs_control* other) {
  if (other == this) return;
  InternalSwap(other);
}
void mcs_control::InternalSwap(mcs_control* other) {
  using std::swap;
  mcs_.InternalSwap(&other->mcs_);
  swap(ran_index_, other->ran_index_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata mcs_control::GetMetadata() const {
  protobuf_control_5fmcs_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_control_5fmcs_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::mcs_control* Arena::CreateMaybeMessage< ::mcs_control >(Arena* arena) {
  return Arena::CreateInternal< ::mcs_control >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
